Gpu
Cytnx-dev/Cytnx pull request #229
Opened 2023-08-07 16:54 UTC by jeffry1829

fix CMakeList output LD_LIBRARY file
rewrite cuGesvd(still not working)
add equivelem api for Tensor&Storage

2023-08-07 17:46 UTC, jeffry1829 commented
I found the way to fix cuGesvd, will commit soon

2023-08-07 23:43 UTC, kaihsin requested changes

2023-08-07 23:43 UTC, kaihsin commented on clang-formater.sh
btw, you can just install `pre-commit` tool, it will automatically format for you everytime you `git commit` (See Developer_tools/)

2023-08-07 23:43 UTC, kaihsin commented on include/Tensor.hpp
Maybe renaming it to approx_eq or eq_approx?

2023-08-07 23:43 UTC, kaihsin commented on src/BoolStorage.cpp
This will not work. if the rhs is not bool, this will fail. Same as other type. 
Also, approx eq you will only need for floating types. So basically for each Storage type, you need to have all the data types (e.g. 

ex: 

BoolStorage:

     bool approx_eq_d(const Storage/or intrusive_ptr<Storage_base>, double tol);
     bool approx_eq_f(const Storage/or intrusive_ptr<Storage_base>, double tol);   
     bool approx_eq_cd(const Storage/or intrusive_ptr<Storage_base>, double tol);
     bool approx_eq_cf(const Storage/or intrusive_ptr<Storage_base>, double tol);
    ......

2023-08-07 23:43 UTC, kaihsin commented on include/Storage.hpp
See below

2023-08-07 23:43 UTC, kaihsin commented on src/linalg/Gesvd.cpp
The second one you don't need to permute the input tensor! you only need to 

1. make the cusolver do hermitian conjugate (with CUDA_H or something like that) 
2. swap the return U, Vt -> Vt -> U
3. permute/conjugate the U and Vt

2023-08-08 11:21 UTC, jeffry1829 commented on src/linalg/Gesvd.cpp
I don't understand why I swap the N,M passed to cugesvd api didn't transpose the input tensor, I'm kinda stuck in this idea.

Also, I don't find hermitian conjugate parameter passable for cugesvd :(

2023-08-11 10:03 UTC, jeffry1829 commented on src/BoolStorage.cpp
I guess I'll convert input storage to lhs dtype if the type is "less" than lhs.
This way, we can compare elements more naturally

2023-08-11 16:32 UTC, jeffry1829 commented on src/BoolStorage.cpp
fix pushed

2023-08-11 17:34 UTC, jeffry1829 commented on src/linalg/Gesvd.cpp
I suggest we deal with this after this PR

2023-08-12 16:54 UTC, jeffry1829 commented on src/linalg/Gesvd.cpp
Fixed, substitute gesvd with gesvdj

2023-08-13 02:56 UTC, kaihsin requested changes
The scalar will still not work... you can't have only one function because you need to deal with strong/weak type. converting the rhs using .to_<dtype> will not work when lhs is stronger than rhs. In the case rhs is stronger, it will either fail to convert or just give you even non-correct results! 

You need to do for all the types separately, like I do (for example greater())

2023-08-13 03:27 UTC, jeffry1829 commented
But I check the type order first, and then choose to convert lhs or rhs, won’t that work?

2023-08-13 03:29 UTC, jeffry1829 commented
Why it doesn’t work when lhs>rhs? Sorry I don’t get it

2023-08-13 03:45 UTC, jeffry1829 commented
Oh I do the bi-directional astype conversion inside every XXXStorage.cpp
And forgot to do it on Scalar or Tensor approx_eq

2023-08-14 06:04 UTC, kaihsin commented
Yes. Sorry I wasn't being specific

2023-08-14 07:11 UTC, jeffry1829 commented
> Yes. Sorry I wasn't being specific

So does it work if I convert both lhs and rhs in Scalar and Tensor approx_eq?

2023-08-16 06:09 UTC, jeffry1829 commented
commented out approx_eq for this PR.
Note that linalg_Test.BkUt_Svd_truncate1 test failed

2023-08-17 23:01 UTC, kaihsin approved these changes

2023-08-17 23:01 UTC, merged