Add label argument for put_block/put_block_
Cytnx-dev/Cytnx pull request #318
Opened 2023-10-20 07:52 UTC by jeffry1829

2023-10-20 16:56 UTC, kaihsin requested changes

2023-10-20 16:56 UTC, kaihsin commented on pybind/unitensor_py.cpp
I think the keyword args should be `py::arg("qidx")` instead of `py::arg("qnum")`? 

Could you modify them for binding on `get_block` and `put_block`

2023-10-21 17:06 UTC, jeffry1829 commented on pybind/unitensor_py.cpp
done

2023-10-24 19:22 UTC, kaihsin approved these changes

2023-10-24 19:22 UTC, merged