Adding slice set between DenseUniTensor
Cytnx-dev/Cytnx pull request #323
Opened 2023-10-23 09:56 UTC by j9263178

https://github.com/Cytnx-dev/Cytnx/issues/319.

2023-10-24 18:46 UTC, kaihsin requested changes

2023-10-24 18:46 UTC, kaihsin commented on include/UniTensor.hpp
You didn't consider if the  incoming UT has i`s_diag=True` and/or the current UT `is_diag=True`

2023-10-25 21:16 UTC, j9263178 commented on include/UniTensor.hpp
@kaihsin  What's the expected behavior of get/set for `is_diag=True` ut? Currently I assume that user should always regard `is_diag=True` ut as an ut having rank-1 block when doing get/set, so they can only do things like `diag_ut[i]` (they can only access the diag part)  but not `diag_ut[i,j,k]` which might gives the non-diag part. Let me know if you think user should be able to do the latter.

2023-10-25 23:51 UTC, kaihsin commented on include/UniTensor.hpp
It's not the tensor anymore so the user should be able to assign (is_diag=true) block to the UT with dense, and vice versa (which include changing the current tensor to is_diag=false)

2023-10-26 00:29 UTC, j9263178 commented on include/UniTensor.hpp
So to be more specific u want sth like user can slice a diag_true_ut (which create a diag_false_ut since there will be non diag zeros due to the slicing), and user can assign  things(might be an element or a block) to a diag_true_ut which may make it into an dense diag_false_ut.

2023-10-26 00:52 UTC, kaihsin commented
Yes. The most important one is if the incoming Unitensor is diag UT, you
need to make conversion first before assign

On Wed, Oct 25, 2023, 20:30 j9263178 ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On include/UniTensor.hpp
> <https://github.com/Cytnx-dev/Cytnx/pull/323#discussion_r1372442995>:
>
> So to be more specific u want sth like user can slice a diag_true_ut
> (which create a diag_false_ut since there will be non diag zeros due to the
> slicing), and user can assign things(might be an element or a block) to a
> diag_true_ut which may make it into an dense diag_false_ut.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Cytnx-dev/Cytnx/pull/323#discussion_r1372442995>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFCX3SNJSPD5UAIMASTDLCLYBGVIVAVCNFSM6AAAAAA6LZMHQCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOJYGUZDCMRXGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-27 00:30 UTC, kaihsin commented
The behavior currently will be:

Reject all set by unitensor with is_diag=True (both incoming, and currrent instance)

2023-10-29 17:54 UTC, jeffry1829 approved these changes

2023-10-29 17:55 UTC, merged